# Generated by Django 5.2 on 2025-08-04 12:00

import django.core.validators
import django.db.models.deletion
import kpis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Identifier for the external system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('CREATE', 'Create operation'), ('UPDATE', 'Update operation'), ('DELETE', 'Delete operation'), ('ACCESS', 'Access operation'), ('AUTH_FAIL', 'Authentication failure'), ('TOKEN_REFRESH', 'Token refresh'), ('PASSWORD_CHANGE', 'Password change')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('affected_object', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('response_size', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('API', 'API Call'), ('NOTIFICATION', 'Notification')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(blank=True, related_name='directorates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='kpis.directorate')),
                ('kpi_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpis.kpiyear')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='kpis.initiative')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'unique_together': {('initiative', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KPIActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('reason_for_performance', models.TextField(blank=True)),
                ('way_forward', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.directorate')),
            ],
            options={
                'verbose_name': 'Monthly KPI Entry',
                'verbose_name_plural': 'Monthly KPI Entries',
            },
        ),
        migrations.CreateModel(
            name='KPIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=255, upload_to='kpi_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png'])])),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('kpi_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kpis.kpiactual')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('aggregation_type', models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average')], default='SUM', help_text='How to aggregate this KPI across directorates', max_length=3)),
                ('performance_logic', models.CharField(choices=[('HIGHER', 'Higher is better'), ('LOWER', 'Lower is better')], default='HIGHER', help_text='Performance evaluation logic', max_length=6)),
                ('is_corporate', models.BooleanField(default=False, help_text='Whether this is a corporate-level KPI')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.directorate')),
                ('kpi_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.kpiyear')),
            ],
            options={
                'unique_together': {('kpi_year', 'directorate', 'name')},
            },
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='predefined_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.predefinedkpi'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='corporate_kpis',
            field=models.ManyToManyField(blank=True, help_text='Corporate KPIs linked to this initiative', limit_choices_to={'is_corporate': True}, related_name='corporate_initiatives', to='kpis.predefinedkpi'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='linked_kpis',
            field=models.ManyToManyField(blank=True, help_text='Regular KPIs linked to this initiative', related_name='initiatives', to='kpis.predefinedkpi'),
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_open', models.BooleanField(default=False)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('allow_user_targets', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('last_code', models.CharField(blank=True, max_length=6)),
                ('code_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[kpis.models.validate_month])),
                ('year', models.IntegerField(validators=[kpis.models.validate_year])),
                ('status', models.CharField(choices=[('red', 'At Risk'), ('yellow', 'On Track'), ('green', 'Completed'), ('grey', 'On Hold'), ('pink', 'Needs Attention')], max_length=10)),
                ('challenges', models.TextField(blank=True)),
                ('way_forward', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kpis.activity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('activity', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_value', models.FloatField()),
                ('predefined_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.predefinedkpi')),
            ],
            options={
                'unique_together': {('predefined_kpi', 'year', 'month')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='kpiactual',
            unique_together={('predefined_kpi', 'directorate', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='initiative',
            unique_together={('directorate', 'title', 'kpi_year')},
        ),
        migrations.CreateModel(
            name='RevokedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('revocation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('KEY_COMPROMISE', 'Key compromise'), ('CA_COMPROMISE', 'CA compromise'), ('AFFILIATION_CHANGED', 'Affiliation changed'), ('SUPERSEDED', 'Superseded'), ('CESSATION_OF_OPERATION', 'Cessation of operation'), ('CERTIFICATE_HOLD', 'Certificate hold'), ('REMOVE_FROM_CRL', 'Remove from CRL'), ('PRIVILEGE_WITHDRAWN', 'Privilege withdrawn'), ('AA_COMPROMISE', 'AA compromise')], default='UNSPECIFIED', max_length=30)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revoked Certificate',
                'verbose_name_plural': 'Revoked Certificates',
                'indexes': [models.Index(fields=['serial_number'], name='kpis_revoke_serial__5d34de_idx'), models.Index(fields=['revocation_date'], name='kpis_revoke_revocat_3e40b7_idx')],
            },
        ),
    ]
